// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data.EfModels;

#nullable disable

namespace backend.Data.Migrations
{
    [DbContext(typeof(ProjetDbContext))]
    [Migration("20260910133241_ConvertAllNvarcharToMax")]
    partial class ConvertAllNvarcharToMax
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Data.EfModels.BonCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<string>("Po")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeId");

                    b.HasIndex("FournisseurId");

                    b.ToTable("BonCommandes");
                });

            modelBuilder.Entity("backend.Data.EfModels.Capex", b =>
                {
                    b.Property<int>("CapexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapexId"));

                    b.Property<double>("BudgetRestant")
                        .HasColumnType("float")
                        .HasColumnName("BudgetRestant");

                    b.Property<double>("BudgetTotal")
                        .HasColumnType("float");

                    b.Property<string>("NomCapex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CapexId")
                        .HasName("PK__Capex__120BD429C6355FB6");

                    b.ToTable("Capexes", (string)null);
                });

            modelBuilder.Entity("backend.Data.EfModels.Demande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapexId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DateValidateChef")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidateDirecteur")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidateFinance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidationAchat1")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateValidationAchat1");

                    b.Property<DateTime?>("DateValidationAchat2")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateValidationAchat2");

                    b.Property<string>("RFX")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RFX");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Demande__8CE9A8CAB33538E6");

                    b.HasIndex("CapexId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Demandes", (string)null);
                });

            modelBuilder.Entity("backend.Data.EfModels.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Departem__3214EC075C2917C8");

                    b.ToTable("Departements");
                });

            modelBuilder.Entity("backend.Data.EfModels.DetailDemande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int");

                    b.Property<string>("Devis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Prix")
                        .HasColumnType("float");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DetailDe__3214EC07CD94415F");

                    b.HasIndex("DemandeId");

                    b.ToTable("DetailsDemandes", (string)null);
                });

            modelBuilder.Entity("backend.Data.EfModels.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("backend.Data.EfModels.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartementId")
                        .HasColumnType("int")
                        .HasColumnName("DepartementID");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Utilisat__3214EC075DBA5179");

                    b.HasIndex("DepartementId");

                    b.ToTable("Utilisateurs", (string)null);
                });

            modelBuilder.Entity("backend.Data.EfModels.BonCommande", b =>
                {
                    b.HasOne("backend.Data.EfModels.Demande", "Demande")
                        .WithMany()
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.EfModels.Fournisseur", "Fournisseur")
                        .WithMany("BonCommandes")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("backend.Data.EfModels.Demande", b =>
                {
                    b.HasOne("backend.Data.EfModels.Capex", "Capex")
                        .WithMany("Demandes")
                        .HasForeignKey("CapexId")
                        .IsRequired()
                        .HasConstraintName("FK_Demande_Capex");

                    b.HasOne("backend.Data.EfModels.Utilisateur", "Utilisateur")
                        .WithMany("Demandes")
                        .HasForeignKey("UtilisateurId")
                        .IsRequired()
                        .HasConstraintName("FK_Demande_Utilisateur");

                    b.Navigation("Capex");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("backend.Data.EfModels.DetailDemande", b =>
                {
                    b.HasOne("backend.Data.EfModels.Demande", "Demande")
                        .WithMany("DetailDemandes")
                        .HasForeignKey("DemandeId")
                        .IsRequired()
                        .HasConstraintName("FK_DetailDemande_Demande");

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("backend.Data.EfModels.Utilisateur", b =>
                {
                    b.HasOne("backend.Data.EfModels.Departement", "Departement")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("DepartementId")
                        .IsRequired()
                        .HasConstraintName("FK_Utilisateur_Departement");

                    b.Navigation("Departement");
                });

            modelBuilder.Entity("backend.Data.EfModels.Capex", b =>
                {
                    b.Navigation("Demandes");
                });

            modelBuilder.Entity("backend.Data.EfModels.Demande", b =>
                {
                    b.Navigation("DetailDemandes");
                });

            modelBuilder.Entity("backend.Data.EfModels.Departement", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("backend.Data.EfModels.Fournisseur", b =>
                {
                    b.Navigation("BonCommandes");
                });

            modelBuilder.Entity("backend.Data.EfModels.Utilisateur", b =>
                {
                    b.Navigation("Demandes");
                });
#pragma warning restore 612, 618
        }
    }
}
