// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data.EfModels;

#nullable disable

namespace backend.Data.Migrations
{
    [DbContext(typeof(ProjetDbContext))]
    partial class ProjetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Data.EfModels.Capex", b =>
                {
                    b.Property<int>("CapexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapexId"));

                    b.Property<decimal>("BudgetTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NomCapex")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ResteBudget")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CapexId")
                        .HasName("PK__Capex__120BD429C6355FB6");

                    b.ToTable("Capex", (string)null);
                });

            modelBuilder.Entity("backend.Data.EfModels.Demande", b =>
                {
                    b.Property<int>("IdDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDemande");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDemande"));

                    b.Property<int>("CapexId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DateValidateChef")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidateDirecteur")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidateFinance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidation1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidation2")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rfx")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RFx");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("IdDemande")
                        .HasName("PK__Demande__8CE9A8CAB33538E6");

                    b.HasIndex("CapexId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Demande", (string)null);
                });

            modelBuilder.Entity("backend.Data.EfModels.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Departem__3214EC075C2917C8");

                    b.HasIndex(new[] { "Nom" }, "UQ_Nom")
                        .IsUnique();

                    b.ToTable("Departement", (string)null);
                });

            modelBuilder.Entity("backend.Data.EfModels.DetailDemande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int");

                    b.Property<string>("Devis")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DetailDe__3214EC07CD94415F");

                    b.HasIndex("DemandeId");

                    b.ToTable("DetailDemande", (string)null);
                });

            modelBuilder.Entity("backend.Data.EfModels.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartementId")
                        .HasColumnType("int")
                        .HasColumnName("DepartementID");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Utilisat__3214EC075DBA5179");

                    b.HasIndex("DepartementId");

                    b.HasIndex(new[] { "Nom" }, "UQ_NomU")
                        .IsUnique();

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("backend.Data.EfModels.Demande", b =>
                {
                    b.HasOne("backend.Data.EfModels.Capex", "Capex")
                        .WithMany("Demandes")
                        .HasForeignKey("CapexId")
                        .IsRequired()
                        .HasConstraintName("FK_Demande_Capex");

                    b.HasOne("backend.Data.EfModels.Utilisateur", "Utilisateur")
                        .WithMany("Demandes")
                        .HasForeignKey("UtilisateurId")
                        .IsRequired()
                        .HasConstraintName("FK_Demande_Utilisateur");

                    b.Navigation("Capex");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("backend.Data.EfModels.DetailDemande", b =>
                {
                    b.HasOne("backend.Data.EfModels.Demande", "Demande")
                        .WithMany("DetailDemandes")
                        .HasForeignKey("DemandeId")
                        .IsRequired()
                        .HasConstraintName("FK_DetailDemande_Demande");

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("backend.Data.EfModels.Utilisateur", b =>
                {
                    b.HasOne("backend.Data.EfModels.Departement", "Departement")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("DepartementId")
                        .IsRequired()
                        .HasConstraintName("FK_Utilisateur_Departement");

                    b.Navigation("Departement");
                });

            modelBuilder.Entity("backend.Data.EfModels.Capex", b =>
                {
                    b.Navigation("Demandes");
                });

            modelBuilder.Entity("backend.Data.EfModels.Demande", b =>
                {
                    b.Navigation("DetailDemandes");
                });

            modelBuilder.Entity("backend.Data.EfModels.Departement", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("backend.Data.EfModels.Utilisateur", b =>
                {
                    b.Navigation("Demandes");
                });
#pragma warning restore 612, 618
        }
    }
}
